#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Dec 10 14:29:11 2013
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from RecipeFrame import RecipeFrame

class RecipeEditor(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        theRecipeFrame = RecipeFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(theRecipeFrame)
        theRecipeFrame.Show()
        return 1

# end of class RecipeEditor

if __name__ == "__main__":
    gettext.install("theRecipeEditor") # replace with the appropriate catalog name

    theRecipeEditor = RecipeEditor(0)
    theRecipeEditor.MainLoop()